{"name": "Guest explores Ports of Departure", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\guest_explore_ports_steps.py\", line 13, in navigate_ports\n    context.app.top_navigation.click_ports()\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\ncl_qa_challenge_dt_12_12_2019\\pages\\top_navigation.py\", line 14, in click_ports\n    self.wait_for_element_click(*self.PORTS)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\ncl_qa_challenge_dt_12_12_2019\\pages\\base_page.py\", line 39, in wait_for_element_click\n    e.click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    return self.request_encode_body(\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\poolmanager.py\", line 330, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\util\\retry.py\", line 400, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n    raise value.with_traceback(tb)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 665, in urlopen\n    httplib_response = self._make_request(\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 416, in _make_request\n    httplib_response = conn.getresponse()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\http\\client.py\", line 1322, in getresponse\n    response.begin()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\http\\client.py\", line 303, in begin\n    version, status, reason = self._read_status()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\http\\client.py\", line 264, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\n"}, "steps": [{"name": "Given a Guest", "status": "passed", "start": 1588300672908, "stop": 1588300675470}, {"name": "And I am on Homepage", "status": "passed", "start": 1588300675470, "stop": 1588300677750}, {"name": "And I navigated to \"Ports\" page", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\guest_explore_ports_steps.py\", line 13, in navigate_ports\n    context.app.top_navigation.click_ports()\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\ncl_qa_challenge_dt_12_12_2019\\pages\\top_navigation.py\", line 14, in click_ports\n    self.wait_for_element_click(*self.PORTS)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\ncl_qa_challenge_dt_12_12_2019\\pages\\base_page.py\", line 39, in wait_for_element_click\n    e.click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    return self.request_encode_body(\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\poolmanager.py\", line 330, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\util\\retry.py\", line 400, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n    raise value.with_traceback(tb)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 665, in urlopen\n    httplib_response = self._make_request(\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 416, in _make_request\n    httplib_response = conn.getresponse()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\http\\client.py\", line 1322, in getresponse\n    response.begin()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\http\\client.py\", line 303, in begin\n    version, status, reason = self._read_status()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\http\\client.py\", line 264, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\n"}, "start": 1588300677751, "stop": 1588300682143}, {"name": "When I search for \"Honolulu\" port", "status": "skipped", "start": 1588300690158, "stop": 1588300690158}, {"name": "Then Map zoomed to show selected port", "status": "skipped", "start": 1588300690158, "stop": 1588300690158}, {"name": "And Port is on the middle of the map", "status": "skipped", "start": 1588300690158, "stop": 1588300690158}, {"name": "And Port displayed as \"Port Of Departure\"", "status": "skipped", "start": 1588300690158, "stop": 1588300690158}], "start": 1588300663795, "stop": 1588300690158, "uuid": "06e46572-e3bf-4eef-8139-c9a087373f61", "historyId": "ce3be5c05a6ec998e99599a81305feef", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Guest explore Ports of Departure"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}